name: CI
on: 
  pull_request:
    branches: [ main ]
jobs:
  windows-build:
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-24.04 ]
        config: [ Debug, Release ]
    name: PR Build ${{matrix.os}} ${{matrix.config}}
    runs-on: ${{ matrix.os }}
    steps:
    # Setup Environment
    - uses: actions/checkout@v2
      with:
        path: "soup"
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 10.0.x
    - name: Setup Soup Build
      uses: soup-build/setup-soup@v1
      with:
        version: latest

    # Restore Nuget
    - name: DotNet Restore
      run: dotnet restore ./soup/code/generate-sharp/generate-sharp.sln

    # Build Soup
    - name: Soup Where
      run: swhere
    - name: Soup Restore Client
      run: soup restore ./soup/code/client/cli/ -v:d
    - name: Soup Build Client
      run: soup build ./soup/code/client/cli/ -flavor ${{matrix.config}}
    - name: Soup Run Version
      run: soup run ./soup/code/client/cli/ -flavor ${{matrix.config}} -args version
    - name: Soup Restore GenerateTest
      run: soup restore ./soup/code/generate-test/
    - name: Soup Build GenerateTest
      run: soup build ./soup/code/generate-test/ -flavor ${{matrix.config}}
    - name: Soup Build BenchmarkTests
      run: soup build ./soup/code/benchmark-tests/ -flavor ${{matrix.config}}
    # - name: Soup Restore SWhere
    #   run: soup restore ./soup/code/generate-sharp/swhere/
    # - name: Soup Build SWhere
    #   run: soup build ./soup/code/generate-sharp/swhere/ -flavor ${{matrix.config}}
    # - name: Soup Restore PackageManager
    #   run: soup restore ./soup/code/generate-sharp/package-manager/
    # - name: Soup Build PackageManager
    #   run: soup build ./soup/code/generate-sharp/package-manager/ -flavor ${{matrix.config}}
    - name: Soup Restore Tools
      run: soup restore ./soup/code/client/native/
    - name: Soup Build Tools
      run: soup build ./soup/code/client/native/ -flavor ${{matrix.config}}

    # Build DotNet
    - name: DotNet Build
      run: dotnet build -c ${{matrix.config}} --no-restore ./soup/code/generate-sharp/generate-sharp.sln
    - name: DotNet Test
      run: dotnet test -c ${{matrix.config}} --no-build --verbosity normal ./soup/code/generate-sharp/generate-sharp.sln

    # Build Tools
    - name: Soup Restore Print
      run: soup restore ./soup/code/tools/print/
    - name: Soup Build Print
      run: soup build ./soup/code/tools/print/ -flavor ${{matrix.config}}
    - name: Soup Restore Migrate
      run: soup restore ./soup/code/generate-sharp/migrate/
    - name: Soup Build Migrate
      run: soup build ./soup/code/generate-sharp/migrate/ -flavor ${{matrix.config}}

    # Build Samples
    - name: Soup Restore C BuildExtension
      run: soup restore ./soup/samples/c/build-extension/executable/
    - name: Soup Build C BuildExtension
      run: soup build ./soup/samples/c/build-extension/executable/ -flavor ${{matrix.config}}
    - name: Soup Build C ConsoleApplication
      run: soup build ./soup/samples/c/console-application/ -flavor ${{matrix.config}}
    - name: Soup Build C DynamicLibrary
      run: soup build ./soup/samples/c/dynamic-library/application/ -flavor ${{matrix.config}}
    - name: Soup Build C StaticLibrary
      run: soup build ./soup/samples/c/static-library/application/ -flavor ${{matrix.config}}
    - name: Soup Build C WindowsApplication
      if: matrix.os == 'windows-2022'
      run: soup build ./soup/samples/c/windows-application/ -flavor ${{matrix.config}}

    - name: Soup Restore C# BuildExtension
      run: soup restore ./soup/samples/csharp/build-extension/executable/
    - name: Soup Build C# BuildExtension
      run: soup build ./soup/samples/csharp/build-extension/executable/ -flavor ${{matrix.config}}
    - name: Soup Build C# ConsoleApplication
      run: soup build ./soup/samples/csharp/console-application/ -flavor ${{matrix.config}}
    - name: Soup Build C# Library
      run: soup build ./soup/samples/csharp/library/application/ -flavor ${{matrix.config}}

    - name: Soup Restore C++ BuildExtension
      run: soup restore ./soup/samples/cpp/build-extension/executable/
    - name: Soup Build C++ BuildExtension
      run: soup build ./soup/samples/cpp/build-extension/executable/ -flavor ${{matrix.config}}
    - name: Soup Build C++ ConsoleApplication
      run: soup build ./soup/samples/cpp/console-application/ -flavor ${{matrix.config}}
    - name: Soup Build C++ DirectX
      if: matrix.os == 'windows-2022'
      run: soup build ./soup/samples/cpp/directx/ -flavor ${{matrix.config}}
    - name: Soup Build C++ DynamicLibrary
      run: soup build ./soup/samples/cpp/dynamic-library/application/ -flavor ${{matrix.config}}
    - name: Soup Build C++ ModuleDynamicLibrary
      run: soup build ./soup/samples/cpp/module-dynamic-library/application/ -flavor ${{matrix.config}}
    - name: Soup Build C++ ModuleInterface
      run: soup build ./soup/samples/cpp/module-interface/ -flavor ${{matrix.config}}
    - name: Soup Restore C++ ParseJson
      run: soup restore ./soup/samples/cpp/parse-json/
    - name: Soup Build C++ ParseJson
      run: soup build ./soup/samples/cpp/parse-json/ -flavor ${{matrix.config}}
    - name: Soup Build C++ StaticLibrary
      run: soup build ./soup/samples/cpp/static-library/application/ -flavor ${{matrix.config}}
    - name: Soup Build C++ WindowsApplication
      if: matrix.os == 'windows-2022'
      run: soup build ./soup/samples/cpp/windows-application/ -flavor ${{matrix.config}}